### ISSUE TITLE
Pophelps to be added / checked

### ISSUE THREAD

**Issue by petecooper** [textpattern/pophelp#49]
This post should be checkboxes to track work done and outstanding, screenshots and notes go in replies. Please update this post with new pophelps to add or update.

**Sections -> Article URL pattern**

- [x] `section_permlink_mode`
- [x] `upload_plugin` - see https://github.com/textpattern/pophelp/issues/49#issuecomment-559560540
- [x] `timestamp_link` - see https://github.com/textpattern/pophelp/issues/49#issuecomment-578039282

**Prefs -> Publish**

- [x] `override_form_types` - https://github.com/textpattern/textpattern/issues/1553#issuecomment-736899723

**Content -> Write**

- [x] `Override form' - Anything better than this scary text? 'Use form' as suggested by Pete might be nicer. And the corresponding pophelp is largely meaningless. Needs rewriting.

**Comment by petecooper** [comment]
Sections -> Article URL pattern

 
![Screen Shot 2019-11-06 at 09 15 06](https://user-images.githubusercontent.com/226578/68285030-70648c00-0076-11ea-86e6-b0a6b717b831.png)

**Comment by bloatware** [comment]
Oops, thanks, `section_permlink_mode` should be just `permlink_mode`, will fix.

**Comment by petecooper** [comment]
`upload_plugin`:
![Screen Shot 2019-11-28 at 16 54 01](https://user-images.githubusercontent.com/226578/69823183-1895ec80-1200-11ea-9d55-27bcad24ac7f.png)

**Comment by philwareham** [comment]
@bloatware @Bloke could you kindly provide me with some info on how the new plugin upload functionality works? So I can write a pophelp for it. i.e. does it upload PHP files, or compiled plugins - that sort of thing. Cheers!

**Comment by bloatware** [comment]
@philwareham one can upload either PHP file (preferably with plugin help/metadata included) or a zipped archive as outlined [here](https://github.com/textpattern/textpattern/issues/1255#issuecomment-493957904).

**Comment by philwareham** [comment]
@bloatware OK thanks - are these plugins stored (and run) in the database or in the 'plugins' directory?

**Comment by bloatware** [comment]
@philwareham currently they are both disk and db-stored for legacy reasons. They are registered and enabled/disabled via db, but loaded only from disk. Few versions later we could drop db code storage and use `txp_plugins` table only for registry.

**Comment by philwareham** [comment]
OK, thanks. Done and closing.

**Comment by petecooper** [comment]
`timestamp_link`

![Screenshot 2020-01-24 at 08 33 20](https://user-images.githubusercontent.com/226578/73055276-5885f280-3e84-11ea-837f-1499e99c7918.png)

**Comment by petecooper** [comment]
I can't reopen this for some reason - anyone?

**Comment by petecooper** [comment]
![Screenshot 2020-12-02 at 00 15 26](https://user-images.githubusercontent.com/226578/100811861-85574e80-3433-11eb-89bd-4fb29bb34975.png)

**Comment by petecooper** [comment]
`shortcodes`

![Screenshot 2020-12-02 at 18 53 06](https://user-images.githubusercontent.com/226578/100918046-e2a0dd80-34cf-11eb-93d1-4dff301d8512.png)

**Comment by Bloke** [comment]
Shortcodes is a custom media type (thus its name is defined in advanced prefs)
Do we need to define it anyway, since it's a core term?

**Comment by petecooper** [comment]
>Shortcodes is a custom media type (thus its name is defined in advanced prefs)

Ah yes, duh. My bad.

**Comment by philwareham** [comment]
Done. Closing.
